#==============================spring config========================================
spring:
  profiles:
    #???????????application.yaml????profile???????????application.yaml??
    #spring.profiles.active=dev
    active: test
  #freemarker config
  freemarker:
    charset: UTF-8
    content-type: text/html
    request-context-attribute: request
    #??ftl????
    template-loader-path: classpath:/templates
  mvc:
    # ???? /**  ??url??????????? /aa/**  ??html????js?css???????/aa
    static-path-pattern: /res/**
  http:
    encoding:
      #??response??
      force: true
  #i18n config
  messages:
      encoding: UTF-8
      #????????
      basename: /i18n/messages
      always-use-message-format: true
##???
server:
  port: 8087
#==============================logging config========================================
#??log4j2??db??????????????logback??????
#logging.config=classpath:log4j2-spring.xml
logging:
  config: classpath:logback-spring.xml


#==============================local define config========================================
boot:
  base:
    templateSprefix: v1