#==============================spring config========================================
spring:
  profiles:
    #激活配置文件
    #spring.profiles.active=dev
    active: test
  #freemarker config
  freemarker:
    charset: UTF-8
    content-type: text/html
    request-context-attribute: request
    #页面位置
    template-loader-path: classpath:/templates
  mvc:
    #资源文件访问前缀,默认无前缀 /**，  如果配置成 /aa/** ，则访问html，js，css文件时，需要加上：/aa
    static-path-pattern: /res/**
  http:
    encoding:
      force: true
  #i18n config
  messages:
      encoding: UTF-8
      #国际化文件夹
      basename: /i18n/messages
      always-use-message-format: true
##内置tomcat启动服务器端口
server:
  port: 8087
#==============================logging config========================================
#log4j2之前配置下来有问题，先使用logback作为日志工具
#logging.config=classpath:log4j2-spring.xml
logging:
  config: classpath:logback-spring.xml

