[#--公共参数存放--]
[#if Session["user"]??]
    [#assign user=Session["user"] /]
[/#if]
[#assign basePath=request.contextPath /]
[#assign baseResourcePath=basePath+springMacroRequestContext.getWebApplicationContext().getEnvironment().getProperty("local.static-path-pattern") /]
